import type { FlatConfig } from '@typescript-eslint/utils/ts-eslint';

const rules: FlatConfig.Rules = {
  'class-methods-use-this': 'off',
  '@typescript-eslint/class-methods-use-this': 'error',
  'consistent-return': 'off',
  '@typescript-eslint/consistent-return': 'error',
  'default-param-last': 'off',
  '@typescript-eslint/default-param-last': 'error',
  'dot-notation': 'off',
  '@typescript-eslint/dot-notation': 'error',
  'init-declarations': 'off',
  '@typescript-eslint/init-declarations': 'off',
  'max-params': 'off',
  '@typescript-eslint/max-params': 'off',
  'no-array-constructor': 'off',
  '@typescript-eslint/no-array-constructor': 'error',
  'no-dupe-class-members': 'off',
  '@typescript-eslint/no-dupe-class-members': 'off',
  'no-empty-function': 'off',
  '@typescript-eslint/no-empty-function': 'error',
  'no-implied-eval': 'off',
  '@typescript-eslint/no-implied-eval': 'error',
  'no-invalid-this': 'off',
  '@typescript-eslint/no-invalid-this': 'off',
  'no-loop-func': 'off',
  '@typescript-eslint/no-loop-func': 'error',
  'no-magic-numbers': 'off',
  '@typescript-eslint/no-magic-numbers': 'off',
  'no-redeclare': 'off',
  '@typescript-eslint/no-redeclare': 'error',
  'no-restricted-imports': 'off',
  '@typescript-eslint/no-restricted-imports': 'off',
  'no-shadow': 'off',
  '@typescript-eslint/no-shadow': 'error',
  'no-unused-expressions': 'off',
  '@typescript-eslint/no-unused-expressions': 'error',
  'no-unused-private-class-members': 'off',
  '@typescript-eslint/no-unused-private-class-members': 'error',
  'no-unused-vars': 'off',
  '@typescript-eslint/no-unused-vars': 'error',
  'no-use-before-define': 'off',
  '@typescript-eslint/no-use-before-define': ['error', {
    ignoreTypeReferences: true,
    allowNamedExports: false,
    functions: false,
    variables: true,
    typedefs: true,
    classes: true,
    enums: true,
  }],
  'no-useless-constructor': 'off',
  '@typescript-eslint/no-useless-constructor': 'error',
  'prefer-destructuring': 'off',
  '@typescript-eslint/prefer-destructuring': 'off',
  'prefer-promise-reject-errors': 'off',
  '@typescript-eslint/prefer-promise-reject-errors': 'error',
  'require-await': 'off',
  '@typescript-eslint/require-await': 'off',
  'no-return-await': 'off',
  '@typescript-eslint/return-await': 'off',
};

export default rules;
