import type { FlatConfig } from '@typescript-eslint/utils/ts-eslint';

export const stylisticJsxRules: FlatConfig.Rules = {
  '@stylistic/jsx-child-element-spacing': 'error',
  '@stylistic/jsx-closing-bracket-location': ['error', 'line-aligned'],
  '@stylistic/jsx-closing-tag-location': ['error', 'line-aligned'],
  '@stylistic/jsx-curly-brace-presence': ['error', 'never'],
  '@stylistic/jsx-curly-newline': ['error', 'never'],
  '@stylistic/jsx-curly-spacing': ['error', {
    when: 'never',
    children: true,
    attributes: true,
    spacing: {
      objectLiterals: 'never',
    },
  }],
  '@stylistic/jsx-equals-spacing': 'error',
  '@stylistic/jsx-first-prop-new-line': 'error',
  '@stylistic/jsx-function-call-newline': 'error',
  '@stylistic/jsx-indent-props': ['error', 2],
  '@stylistic/jsx-indent': 'off',
  '@stylistic/jsx-max-props-per-line': 'error',
  '@stylistic/jsx-newline': 'error',
  '@stylistic/jsx-one-expression-per-line': ['error', {
    allow: 'non-jsx',
  }],
  '@stylistic/jsx-pascal-case': 'error',
  '@stylistic/jsx-props-no-multi-spaces': 'off',
  '@stylistic/jsx-quotes': 'error',
  '@stylistic/jsx-self-closing-comp': ['error', {
    component: true,
    html: false,
  }],
  '@stylistic/jsx-sort-props': 'off',
  '@stylistic/jsx-tag-spacing': ['error', {
    beforeSelfClosing: 'always',
  }],
  '@stylistic/jsx-wrap-multilines': ['error', {
    declaration: 'parens',
    assignment: 'parens',
    return: 'parens',
    arrow: 'parens',
  }],
};

const rules: FlatConfig.Rules = {
  '@stylistic/array-bracket-newline': 'off',
  '@stylistic/array-bracket-spacing': 'error',
  '@stylistic/array-element-newline': 'off',
  '@stylistic/arrow-parens': ['error', 'as-needed'],
  '@stylistic/arrow-spacing': 'error',
  '@stylistic/block-spacing': 'error',
  '@stylistic/brace-style': 'error',
  '@stylistic/comma-dangle': ['error', 'always-multiline'],
  '@stylistic/comma-spacing': 'error',
  '@stylistic/comma-style': 'error',
  '@stylistic/computed-property-spacing': 'error',
  '@stylistic/dot-location': ['error', 'property'],
  '@stylistic/eol-last': 'error',
  '@stylistic/function-call-argument-newline': ['error', 'consistent'],
  '@stylistic/function-call-spacing': 'error',
  '@stylistic/function-paren-newline': ['error', 'multiline-arguments'],
  '@stylistic/generator-star-spacing': ['error', {
    before: false,
    after: true,
    method: 'neither',
  }],
  '@stylistic/implicit-arrow-linebreak': 'error',
  '@stylistic/indent': ['error', 2, {
    SwitchCase: 1,
  }],
  '@stylistic/indent-binary-ops': ['error', 2],
  '@stylistic/key-spacing': 'error',
  '@stylistic/keyword-spacing': 'error',
  '@stylistic/line-comment-position': 'off',
  '@stylistic/linebreak-style': 'error',
  '@stylistic/lines-around-comment': 'off',
  '@stylistic/lines-between-class-members': ['error', 'always', {
    exceptAfterSingleLine: true,
  }],
  '@stylistic/max-len': ['error', {
    code: 140,
    tabWidth: 2,
    ignoreUrls: true,
  }],
  '@stylistic/max-statements-per-line': 'off',
  '@stylistic/member-delimiter-style': 'error',
  '@stylistic/multiline-comment-style': 'off',
  '@stylistic/multiline-ternary': 'off',
  '@stylistic/new-parens': 'error',
  '@stylistic/newline-per-chained-call': ['error', {
    ignoreChainWithDepth: 4,
  }],
  '@stylistic/no-confusing-arrow': 'error',
  '@stylistic/no-extra-parens': 'off',
  '@stylistic/no-extra-semi': 'error',
  '@stylistic/no-floating-decimal': 'error',
  '@stylistic/no-mixed-operators': ['error', {
    allowSamePrecedence: false,
    groups: [
      ['%', '**'],
      ['%', '+'],
      ['%', '-'],
      ['%', '*'],
      ['%', '/'],
      ['/', '*'],
      ['&', '|', '<<', '>>', '>>>'],
      ['==', '!=', '===', '!=='],
      ['&&', '||'],
    ],
  }],
  '@stylistic/no-mixed-spaces-and-tabs': 'error',
  '@stylistic/no-multi-spaces': 'error',
  '@stylistic/no-multiple-empty-lines': ['error', {
    max: 1,
  }],
  '@stylistic/no-tabs': 'error',
  '@stylistic/no-trailing-spaces': 'error',
  '@stylistic/no-whitespace-before-property': 'error',
  '@stylistic/nonblock-statement-body-position': 'error',
  '@stylistic/object-curly-newline': 'off',
  '@stylistic/object-curly-spacing': ['error', 'always'],
  '@stylistic/object-property-newline': ['error', {
    allowAllPropertiesOnSameLine: true,
  }],
  '@stylistic/one-var-declaration-per-line': ['error', 'always'],
  '@stylistic/operator-linebreak': ['error', 'before', {
    overrides: {
      '=': 'none',
    },
  }],
  '@stylistic/padded-blocks': 'off',
  '@stylistic/padding-line-between-statements': ['error', {
    // eslint-disable-next-line unicorn/prevent-abbreviations
    prev: '*',
    blankLine: 'always',
    next: [
      'if',
      'for',
      'function',
      'switch',
      'do',
      'while',
      'try',
    ],
  }],
  '@stylistic/quote-props': ['error', 'as-needed', {
    keywords: false,
    unnecessary: true,
    numbers: false,
  }],
  '@stylistic/quotes': ['error', 'single', {
    avoidEscape: true,
  }],
  '@stylistic/rest-spread-spacing': 'error',
  '@stylistic/semi': 'error',
  '@stylistic/semi-spacing': 'error',
  '@stylistic/semi-style': 'error',
  '@stylistic/space-before-blocks': 'error',
  '@stylistic/space-before-function-paren': ['error', {
    asyncArrow: 'always',
    anonymous: 'always',
    named: 'never',
  }],
  '@stylistic/space-in-parens': 'error',
  '@stylistic/space-infix-ops': 'error',
  '@stylistic/space-unary-ops': 'error',
  '@stylistic/spaced-comment': ['error', 'always', {
    line: {
      exceptions: ['-', '+'],
      markers: ['=', '!', '/'],
    },
    block: {
      exceptions: ['-', '+'],
      markers: ['=', '!', ':', '::'],
    },
  }],
  '@stylistic/switch-colon-spacing': 'error',
  '@stylistic/template-curly-spacing': 'error',
  '@stylistic/template-tag-spacing': 'error',
  '@stylistic/type-annotation-spacing': 'off',
  '@stylistic/type-generic-spacing': 'off',
  '@stylistic/type-named-tuple-spacing': 'off',
  '@stylistic/wrap-iife': 'error',
  '@stylistic/wrap-regex': 'off',
  '@stylistic/yield-star-spacing': 'error',
};

export default rules;
