import type { FlatConfig } from '@typescript-eslint/utils/ts-eslint';

const rules: FlatConfig.Rules = {
  'react/boolean-prop-naming': 'error',
  'react/button-has-type': 'off',
  'react/checked-requires-onchange-or-readonly': 'off',
  'react/default-props-match-prop-types': 'off',
  'react/destructuring-assignment': 'off',
  'react/display-name': 'off',
  'react/forbid-component-props': 'off',
  'react/forbid-dom-props': 'off',
  'react/forbid-elements': 'off',
  'react/forbid-foreign-prop-types': 'off',
  'react/forbid-prop-types': 'off',
  'react/forward-ref-uses-ref': 'off',
  'react/function-component-definition': ['error', {
    namedComponents: 'function-declaration',
    unnamedComponents: 'arrow-function',
  }],
  'react/hook-use-state': 'off',
  'react/iframe-missing-sandbox': 'off',
  'react/jsx-boolean-value': 'off',
  'react/jsx-child-element-spacing': 'off',
  'react/jsx-closing-bracket-location': 'off',
  'react/jsx-closing-tag-location': 'off',
  'react/jsx-curly-spacing': 'off',
  'react/jsx-curly-newline': 'off',
  'react/jsx-equals-spacing': 'off',
  'react/jsx-filename-extension': ['error', {
    extensions: ['.tsx'],
  }],
  'react/jsx-first-prop-new-line': 'off',
  'react/jsx-handler-names': ['error', {
    checkLocalVariables: true,
  }],
  'react/jsx-indent': 'off',
  'react/jsx-indent-props': 'off',
  'react/jsx-key': 'off',
  'react/jsx-max-depth': 'off',
  'react/jsx-max-props-per-line': 'off',
  'react/jsx-newline': 'off',
  'react/jsx-no-bind': ['error', {
    // eslint-disable-next-line @typescript-eslint/naming-convention
    ignoreDOMComponents: true,
    // eslint-disable-next-line unicorn/prevent-abbreviations
    ignoreRefs: true,
    allowArrowFunctions: true,
    allowFunctions: true,
    allowBind: false,
  }],
  'react/jsx-no-comment-textnodes': 'off',
  'react/jsx-no-constructed-context-values': 'off',
  'react/jsx-no-duplicate-props': 'off',
  'react/jsx-no-leaked-render': 'off',
  'react/jsx-no-literals': 'off',
  'react/jsx-no-script-url': 'off',
  'react/jsx-no-target-blank': 'off',
  'react/jsx-no-useless-fragment': 'off',
  'react/jsx-one-expression-per-line': 'off',
  'react/jsx-no-undef': 'off',
  'react/jsx-curly-brace-presence': 'off',
  'react/jsx-pascal-case': 'off',
  'react/jsx-fragments': 'off',
  'react/jsx-props-no-multi-spaces': 'off',
  'react/jsx-props-no-spreading': 'off',
  'react/jsx-props-no-spread-multi': 'error',
  'react/jsx-sort-props': 'off',
  'react/jsx-tag-spacing': 'off',
  'react/jsx-uses-react': 'off',
  'react/jsx-uses-vars': 'off',
  'react/jsx-wrap-multilines': 'off',
  'react/no-invalid-html-attribute': 'error',
  'react/no-access-state-in-setstate': 'off',
  'react/no-adjacent-inline-elements': 'error',
  'react/no-array-index-key': 'off',
  'react/no-arrow-function-lifecycle': 'off',
  'react/no-children-prop': 'off',
  'react/no-danger': 'off',
  'react/no-danger-with-children': 'off',
  'react/no-deprecated': 'off',
  'react/no-did-mount-set-state': 'off',
  'react/no-did-update-set-state': 'off',
  'react/no-direct-mutation-state': 'off',
  'react/no-find-dom-node': 'off',
  'react/no-is-mounted': 'off',
  'react/no-multi-comp': 'error',
  'react/no-namespace': 'off',
  'react/no-set-state': 'off',
  'react/no-string-refs': 'off',
  'react/no-redundant-should-component-update': 'off',
  'react/no-render-return-value': 'off',
  'react/no-this-in-sfc': 'error',
  'react/no-typos': 'error',
  'react/no-unescaped-entities': 'error',
  'react/no-unknown-property': 'off',
  'react/no-unsafe': 'off',
  'react/no-unstable-nested-components': 'off',
  'react/no-unused-class-component-methods': 'off',
  'react/no-unused-prop-types': 'off',
  'react/no-unused-state': 'off',
  'react/no-object-type-as-default-prop': 'off',
  'react/no-will-update-set-state': 'off',
  'react/prefer-es6-class': 'off',
  'react/prefer-exact-props': 'off',
  'react/prefer-read-only-props': 'off',
  'react/prefer-stateless-function': 'off',
  'react/prop-types': 'off',
  'react/react-in-jsx-scope': 'off',
  'react/require-default-props': 'off',
  'react/require-optimization': 'off',
  'react/require-render-return': 'off',
  'react/self-closing-comp': 'off',
  'react/sort-comp': 'off',
  'react/sort-default-props': 'off',
  'react/sort-prop-types': 'off',
  'react/state-in-constructor': 'off',
  'react/static-property-placement': 'off',
  'react/style-prop-object': 'off',
  'react/void-dom-elements-no-children': 'off',
};

export default rules;
