import type { FlatConfig } from '@typescript-eslint/utils/ts-eslint';

const rules: FlatConfig.Rules = {
  'react-x/jsx-dollar': 'error',
  'react-x/jsx-key-before-spread': 'error',
  'react-x/jsx-no-comment-textnodes': 'error',
  'react-x/jsx-shorthand-boolean': ['error', -1],
  'react-x/jsx-shorthand-fragment': 'error',
  'react-x/no-access-state-in-setstate': 'error',
  'react-x/no-array-index-key': 'error',
  'react-x/no-children-count': 'error',
  'react-x/no-children-for-each': 'error',
  'react-x/no-children-map': 'error',
  'react-x/no-children-only': 'error',
  'react-x/no-children-prop': 'error',
  'react-x/no-children-to-array': 'error',
  'react-x/no-class-component': 'error',
  'react-x/no-clone-element': 'error',
  'react-x/no-component-will-mount': 'error',
  'react-x/no-component-will-receive-props': 'error',
  'react-x/no-component-will-update': 'error',
  'react-x/no-context-provider': 'error',
  'react-x/no-create-ref': 'error',
  'react-x/no-direct-mutation-state': 'error',
  'react-x/no-forward-ref': 'error',
  'react-x/no-leaked-conditional-rendering': 'error',
  'react-x/no-missing-component-display-name': 'error',
  'react-x/no-missing-context-display-name': 'error',
  'react-x/no-missing-key': 'error',
  'react-x/no-nested-component-definitions': 'error',
  'react-x/no-nested-lazy-component-declarations': 'error',
  'react-x/no-redundant-should-component-update': 'error',
  'react-x/no-set-state-in-component-did-mount': 'error',
  'react-x/no-set-state-in-component-did-update': 'error',
  'react-x/no-set-state-in-component-will-update': 'error',
  'react-x/no-unsafe-component-will-mount': 'error',
  'react-x/no-unsafe-component-will-receive-props': 'error',
  'react-x/no-unsafe-component-will-update': 'error',
  'react-x/no-unstable-context-value': 'error',
  'react-x/no-unstable-default-props': 'error',
  'react-x/no-unused-class-component-members': 'error',
  'react-x/no-unused-state': 'error',
  'react-x/no-use-context': 'error',
  'react-x/no-useless-fragment': 'error',
  'react-x/prefer-destructuring-assignment': 'off',
  'react-x/prefer-namespace-import': 'error',
};

export default rules;
