import type { FlatConfig } from '@typescript-eslint/utils/ts-eslint';

const rules: FlatConfig.Rules = {
  'vue/comment-directive': 'error',
  'vue/jsx-uses-vars': 'error',
  'vue/multi-word-component-names': 'off',
  'vue/no-arrow-functions-in-watch': 'error',
  'vue/no-async-in-computed-properties': 'error',
  'vue/no-child-content': 'error',
  'vue/no-computed-properties-in-data': 'error',
  'vue/no-custom-modifiers-on-v-model': 'off',
  'vue/no-deprecated-data-object-declaration': 'error',
  'vue/no-deprecated-delete-set': 'error',
  'vue/no-deprecated-destroyed-lifecycle': 'error',
  'vue/no-deprecated-dollar-listeners-api': 'error',
  'vue/no-deprecated-dollar-scopedslots-api': 'error',
  'vue/no-deprecated-events-api': 'error',
  'vue/no-deprecated-filter': 'error',
  'vue/no-deprecated-functional-template': 'error',
  'vue/no-deprecated-html-element-is': 'error',
  'vue/no-deprecated-inline-template': 'error',
  'vue/no-deprecated-model-definition': 'error',
  'vue/no-deprecated-props-default-this': 'error',
  'vue/no-deprecated-router-link-tag-prop': 'error',
  'vue/no-deprecated-scope-attribute': 'error',
  'vue/no-deprecated-slot-attribute': 'error',
  'vue/no-deprecated-slot-scope-attribute': 'error',
  'vue/no-deprecated-v-bind-sync': 'error',
  'vue/no-deprecated-v-is': 'error',
  'vue/no-deprecated-v-on-native-modifier': 'error',
  'vue/no-deprecated-v-on-number-modifiers': 'error',
  'vue/no-deprecated-vue-config-keycodes': 'error',
  'vue/no-dupe-keys': 'error',
  'vue/no-dupe-v-else-if': 'error',
  'vue/no-duplicate-attributes': 'error',
  'vue/no-export-in-script-setup': 'error',
  'vue/no-expose-after-await': 'error',
  'vue/no-lifecycle-after-await': 'error',
  'vue/no-multiple-template-root': 'error',
  'vue/no-mutating-props': 'error',
  'vue/no-parsing-error': 'error',
  'vue/no-ref-as-operand': 'error',
  'vue/no-reserved-component-names': 'error',
  'vue/no-reserved-keys': 'error',
  'vue/no-reserved-props': 'error',
  'vue/no-shared-component-data': 'error',
  'vue/no-side-effects-in-computed-properties': 'error',
  'vue/no-template-key': 'error',
  'vue/no-textarea-mustache': 'error',
  'vue/no-unused-components': 'error',
  'vue/no-unused-vars': 'error',
  'vue/no-use-computed-property-like-method': 'error',
  'vue/no-use-v-if-with-v-for': 'error',
  'vue/no-useless-template-attributes': 'error',
  'vue/no-v-text-v-html-on-component': 'error',
  'vue/no-watch-after-await': 'error',
  'vue/prefer-import-from-vue': 'error',
  'vue/require-component-is': 'error',
  'vue/require-prop-type-constructor': 'error',
  'vue/require-render-return': 'error',
  'vue/require-slots-as-functions': 'error',
  'vue/require-toggle-inside-transition': 'error',
  'vue/require-v-for-key': 'error',
  'vue/require-valid-default-prop': 'error',
  'vue/return-in-computed-property': 'error',
  'vue/return-in-emits-validator': 'error',
  'vue/use-v-on-exact': 'error',
  'vue/valid-attribute-name': 'error',
  'vue/valid-define-emits': 'error',
  'vue/valid-define-options': 'error',
  'vue/valid-define-props': 'error',
  'vue/valid-next-tick': 'error',
  'vue/valid-template-root': 'error',
  'vue/valid-v-bind': 'error',
  'vue/valid-v-cloak': 'error',
  'vue/valid-v-else-if': 'error',
  'vue/valid-v-else': 'error',
  'vue/valid-v-for': 'error',
  'vue/valid-v-html': 'error',
  'vue/valid-v-if': 'error',
  'vue/valid-v-is': 'error',
  'vue/valid-v-memo': 'error',
  'vue/valid-v-model': 'error',
  'vue/valid-v-on': 'error',
  'vue/valid-v-once': 'error',
  'vue/valid-v-pre': 'error',
  'vue/valid-v-show': 'error',
  'vue/valid-v-slot': 'error',
  'vue/valid-v-text': 'error',
  'vue/attribute-hyphenation': 'error',
  'vue/component-definition-name-casing': 'error',
  'vue/first-attribute-linebreak': 'error',
  'vue/html-closing-bracket-newline': 'error',
  'vue/html-closing-bracket-spacing': 'error',
  'vue/html-end-tags': 'error',
  'vue/html-indent': 'error',
  'vue/html-quotes': 'error',
  'vue/html-self-closing': ['error', {
    html: {
      void: 'never',
      normal: 'never',
      component: 'always',
    },
    svg: 'never',
    math: 'never',
  }],
  'vue/max-attributes-per-line': 'error',
  'vue/multiline-html-element-content-newline': 'error',
  'vue/mustache-interpolation-spacing': 'error',
  'vue/no-multi-spaces': 'error',
  'vue/no-spaces-around-equal-signs-in-attribute': 'error',
  'vue/no-template-shadow': 'error',
  'vue/one-component-per-file': 'error',
  'vue/prop-name-casing': 'error',
  'vue/require-default-prop': 'error',
  'vue/require-explicit-emits': 'error',
  'vue/require-prop-types': 'error',
  'vue/singleline-html-element-content-newline': 'error',
  'vue/v-bind-style': 'error',
  'vue/v-on-event-hyphenation': 'error',
  'vue/v-on-style': 'error',
  'vue/v-slot-style': 'error',
  'vue/attributes-order': ['error', {
    order: [
      'DEFINITION',
      'LIST_RENDERING',
      'CONDITIONALS',
      'RENDER_MODIFIERS',
      'GLOBAL',
      'UNIQUE',
      'SLOT',
      'TWO_WAY_BINDING',
      'OTHER_DIRECTIVES',
      'ATTR_DYNAMIC',
      'ATTR_STATIC',
      'ATTR_SHORTHAND_BOOL',
      'EVENTS',
      'CONTENT',
    ],
  }],
  'vue/block-order': ['error', {
    order: ['script', 'template', 'style'],
  }],
  'vue/no-lone-template': 'error',
  'vue/no-multiple-slot-args': 'error',
  'vue/no-required-prop-with-default': 'error',
  'vue/no-v-html': 'off',
  'vue/order-in-components': 'error',
  'vue/this-in-template': 'error',
  'vue/block-lang': ['error', {
    script: {
      lang: 'ts',
      allowNoLang: false,
    },
  }],
  'vue/block-tag-newline': ['error', {
    singleline: 'always',
    multiline: 'always',
    maxEmptyLines: 0,
  }],
  'vue/component-api-style': 'error',
  'vue/component-name-in-template-casing': 'error',
  'vue/component-options-name-casing': 'error',
  'vue/custom-event-name-casing': 'error',
  'vue/define-emits-declaration': 'error',
  'vue/define-macros-order': 'error',
  'vue/define-props-declaration': 'error',
  'vue/define-props-destructuring': 'off',
  'vue/enforce-style-attribute': 'off',
  'vue/html-button-has-type': 'error',
  'vue/html-comment-content-newline': 'error',
  'vue/html-comment-content-spacing': 'error',
  'vue/html-comment-indent': 'error',
  'vue/match-component-file-name': ['error', {
    extensions: ['vue'],
    shouldMatchCase: true,
  }],
  'vue/match-component-import-name': 'error',
  'vue/max-lines-per-block': ['error', {
    script: 400,
  }],
  'vue/max-props': 'off',
  'vue/max-template-depth': 'off',
  'vue/new-line-between-multi-line-property': 'error',
  'vue/next-tick-style': 'error',
  'vue/no-bare-strings-in-template': 'off',
  'vue/no-boolean-default': 'off',
  'vue/no-duplicate-attr-inheritance': 'error',
  'vue/no-duplicate-class-names': 'error',
  'vue/no-empty-component-block': 'error',
  'vue/no-import-compiler-macros': 'error',
  'vue/no-literals-in-template': 'off',
  'vue/no-multiple-objects-in-class': 'error',
  'vue/no-negated-v-if-condition': 'error',
  'vue/no-potential-component-option-typo': 'error',
  'vue/no-ref-object-reactivity-loss': 'off',
  'vue/no-restricted-block': 'off',
  'vue/no-restricted-call-after-await': 'off',
  'vue/no-restricted-class': 'off',
  'vue/no-restricted-component-names': 'off',
  'vue/no-restricted-component-options': 'off',
  'vue/no-restricted-custom-event': 'off',
  'vue/no-restricted-html-elements': 'off',
  'vue/no-restricted-props': 'off',
  'vue/no-restricted-static-attribute': 'off',
  'vue/no-restricted-v-bind': 'off',
  'vue/no-restricted-v-on': 'off',
  'vue/no-root-v-if': 'off',
  'vue/no-setup-props-reactivity-loss': 'off',
  'vue/no-static-inline-styles': 'error',
  'vue/no-template-target-blank': 'error',
  'vue/no-this-in-before-route-enter': 'error',
  'vue/no-undef-components': ['error', {
    ignorePatterns: [
      '^Router(View|Link)$',
    ],
  }],
  'vue/no-undef-directives': 'error',
  'vue/no-undef-properties': 'off',
  'vue/no-unsupported-features': 'off',
  'vue/no-unused-emit-declarations': 'error',
  'vue/no-unused-properties': ['error', {
    deepData: true,
    groups: [
      'inject',
      'props',
      'data',
      'computed',
      'methods',
      'setup',
    ],
  }],
  'vue/no-unused-refs': 'error',
  'vue/no-use-v-else-with-v-for': 'error',
  'vue/no-useless-mustaches': ['error', {
    ignoreStringEscape: true,
  }],
  'vue/no-useless-v-bind': ['error', {
    ignoreStringEscape: true,
  }],
  'vue/no-v-text': 'error',
  'vue/padding-line-between-blocks': 'error',
  'vue/padding-line-between-tags': 'error',
  'vue/padding-lines-in-component-definition': ['error', {
    groupSingleLineProperties: false,
    betweenOptions: 'always',
    withinOption: {
      components: 'never',
      mixins: 'never',
      // eslint-disable-next-line unicorn/prevent-abbreviations
      props: {
        betweenItems: 'always',
        withinEach: 'never',
      },
      emits: 'never',
      data: 'never',
      computed: {
        betweenItems: 'always',
        withinEach: 'never',
      },
      watch: {
        betweenItems: 'always',
        withinEach: 'never',
      },
      methods: {
        betweenItems: 'always',
        withinEach: 'never',
      },
    },
  }],
  'vue/prefer-define-options': 'error',
  'vue/prefer-prop-type-boolean-first': 'off',
  'vue/prefer-separate-static-class': 'error',
  'vue/prefer-single-event-payload': 'error',
  'vue/prefer-true-attribute-shorthand': 'off',
  'vue/prefer-use-template-ref': 'error',
  'vue/require-default-export': 'error',
  'vue/require-direct-export': 'error',
  'vue/require-emit-validator': 'off',
  'vue/require-explicit-slots': 'error',
  'vue/require-expose': 'off',
  'vue/require-macro-variable-name': 'error',
  'vue/require-name-property': 'off',
  'vue/require-prop-comment': 'off',
  'vue/require-typed-object-prop': 'error',
  'vue/require-typed-ref': 'error',
  'vue/restricted-component-names': 'error',
  'vue/script-indent': ['error', 2, {
    baseIndent: 1,
    switchCase: 1,
  }],
  'vue/slot-name-casing': 'error',
  'vue/sort-keys': 'off',
  'vue/static-class-names-order': 'off',
  'vue/v-for-delimiter-style': 'error',
  'vue/v-if-else-key': 'error',
  'vue/v-on-handler-style': 'error',
};

export default rules;
